version: "3.8"

services:
  app:
    image: ghcr.io/mathiasschoettle/tooloftools:main
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: toft

  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    volumes:
      - toft-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: toft

volumes:
  toft-mysql-data: